---
- name: Enable ocroot account with hwroot password
  shell: echo "ocroot:hwroot" | chpasswd

- name: Start then stop the firewall as the OCMP VNFC defers its configuration to the end user
  service:
    name: iptables
    state: started
- service:
    name: iptables
    state: stopped

- name: Start ocmp base
  shell: /opt/OC/bin/ocmpStart

# NOTE: ocmp-bre status returns 1 if running, 0 if not.
- name: Start ocmp bre
  shell: /usr/bin/ocmp-bre status && /usr/bin/ocmp-bre start || echo ocmp-bre already started