---
driver:
  name: azurerm
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
  location: <%= ENV['AZURE_LOCATION'] %>
  machine_size: <%= ENV['AZURE_FLAVOR'] %>
  
transport:
  ssh_key: <%= ENV['AZURE_SSH_KEY'] %>

provisioner:
  name: nodes

verifier:
  name: inspec

platforms:
  - name: pgsql
    machine_size: <%= ENV['AZURE_FLAVOR'] %>
    run_list:
      - recipe[hpe_mse::base]
    driver_config:
      image_urn: <%= ENV['AZURE_IMAGE'] %>
      vm_name: pgsql.mse.azure
      vm_tags:
        ostype: linux
        distro: <%= ENV['AZURE_DISTRO'] %>
  - name: ems
    machine_size: <%= ENV['AZURE_FLAVOR'] %>
    run_list:
      - recipe[hpe_mse::ems]
    driver_config:
      image_urn: <%= ENV['AZURE_IMAGE'] %>
      vm_name: ems.mse.azure
      vm_tags:
        ostype: linux
        distro: <%= ENV['AZURE_DISTRO'] %>
  
suites:
  - name: mse
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      mse:
        install:
          # URL providing MSE ISO images
          isoUrl: <%= ENV['MSE_ISO_URL'] %>
          iso:
            # ISO image delivering the MSE automated deployer engine
            engine: <%= ENV['MSE_ENGINE'] %>
            # List of ISO images delivering the MSE products
            product: <%= ENV['MSE_PRODUCT'] %>
          # List of yum repositories to be used for MSE automated deployer installation
          yumRepo: <%= ENV['MSE_YUM_REPO'] %>
          # URL providing common ssh keys: id_rsa, ssh_host_ecdsa_key, ssh_host_ed25519_key, ssh_host_rsa_key and their relative pub files
          sshKeysUrl: <%= ENV['MSE_SSH_KEYS_URL'] %>
        deploy:
          descriptor: |+
            # -------------------------------------------------------------
            # MSE 2 nodes: ems and Pgsql database, refreshed on one node
            # MSE Descriptor generated by the builder 2018-08-02 Version 2.36
            # Build date: Sat Sep 08 2018 22:13:13 GMT+0200 (heure d’été d’Europe centrale)
            # PRE REQUISISTES ON THE NODE RUNNING THE UNATTENDED NIVR SETUP
            # 1. The management network is up and running
            # 2.1 The command 'hostname' returns a fully qualified domain name used for node identification within the cluster
            # 2.2 The command 'hostname -i' returns the node IPV4 address on the MGMT network
            # OR
            # 2. /etc/sysconfig/network has a fully qualified domain name at the HOSTNAME entry
            # 3. MSE bits are available as:
            # 3.1 ISOs images on the file system in /var/opt/OC/iso or 
            # 3.2 YUM repositories listed in YUM_REPO_LIST and IS_YUM_REPO=yes
            # -------------------------------------------------------------


            # ------------------------------- #
            # Network interfaces definition   #
            # ------------------------------- #
            MGMT_DEVICE=eth0
            MGMT_NETMASK=255.255.248.0

            # ------------------------------- #
            # Nodes and roles definition      #
            # ------------------------------- #

            # VNF Element Manager      #
            NIVR_EMS_NAME=ems.$(hostname -d)
            NIVR_EMS_IP_ADDR=<@= node['mse']['map']['ems']['ipaddress'] @>

            # ------------------------------- #
            # SEE Clusters                    #
            # ------------------------------- #
            # SEE Simplex      #
            # SEE Primary      #

            # SEE Secondary      #

            # SEE Witness      #

            # SEE additional nodes      #

            # HTTP Load Balancer Primary node   #

            # HTTP Load Balancer Secondary node   #

            # HTTP Load balancer virtual IP      #
            SEE_VIP_NAME=${VHTTP_NAME}
            RSLMF_VIP_NAME=${VHTTP_NAME}

            # Pgsql database
            # -Standalone: one single entry pointing to the Pgsql node
            # -Linux HA: one single entry defining the VIP of the Pgsql resource
            # -Static cluster: list of SEE nodes co-locating Pgsql, the first being the initial master
            PGSQL_HOST=( pgsql.$(hostname -d) )
            PGSQL_IP_ADDR=( <@= node['mse']['map']['pgsql']['ipaddress'] @> )

            #-------------------------------------------------#
            # Groups for service continuity upon upgrade
            # IP addresses preferred to address unresolved names
            #--------------------------------------------------#
            NIVR_REFRESH_SCHEDULE=(
                <@= node['mse']['map']['pgsql']['ipaddress'] @> \
            )

            # ------------------------------- #
            # Security                        #
            # ------------------------------- #
            # Certification authority for self signed certificates
            CERT_AUTH_ALIAS="nfvCert"
            # Certification authority password
            CERT_AUTH_PASSWORD="nfvCert"
            # Password for Linux HA administrator account (hacluster) and Redis access control; enforced for all Redis resources, default value: hacluster
            NIVRDB_LINUXHA_PASSWORD="hacluster"

            # ------------------------------- #
            # Miscellaneous properties        #
            # ------------------------------- #
            # node collecting SNMP traps emitted by all the VNF members, typically the VNF EMS
            SNMP_TRAP_DESTINATION="${NIVR_EMS_IP_ADDR}"
            # YUM repositories list
            YUM_REPO_LIST=centos*,updates*,base*
            [ "$YUM_REPO_LIST" != "" ] && IS_YUM_REPO=yes || IS_YUM_REPO=no

            # ------------------------ #
            # Redis Sentinel Instances #
            # ------------------------ #

            # ------------------------------- #
            #    OCSNF policy                 #
            # ------------------------------- #

            # ------------------------------- #
            #       Messaging Framework       #
            # ------------------------------- #

            # ------------------------------- #
            # Messaging Framework Application #
            # ------------------------------- #

            # ------------------------------- #
            #       Messaging Gateway       #
            # ------------------------------- #

            # ------------------------------- #
            #    Messaging Gateway Services   #
            # ------------------------------- #

            # ------------------------------- #
            # OCCP countries                  #
            # ------------------------------- #

            # ------------------------------- #
            # OCCP switching points           #
            # ------------------------------- #

            # ------------------------------- #
            # OCCP media servers              #
            # ------------------------------- #

            # ------------------------------- #
            #  TCAP connectivity providers    #
            # ------------------------------- #

            # ------------------------------- #
            # MRF adapters                    #
            # ------------------------------- #

            # ------------------------------- #
            # Diameter     providers          #
            # ------------------------------- #

            # ------------------------------- #
            # Ucp and Smpp providers          #
            # ------------------------------- #

            # ------------------------------- #
            # SMPP sessions                   #
            # ------------------------------- #

            # ------------------------------- #
            # SMPP profiles                   #
            # ------------------------------- #

            # ------------------------------- #
            # SMPP pairs                      #
            # ------------------------------- #

            # ------------------------------- #
            # JDBC and LDAP data sources      #
            # ------------------------------- #

            # ------------- #
            # LDAP profiles #
            # ------------- #

            # --------------- #
            # SOAP connectors #
            # --------------- #

            # ------------------------- #
            # SOAP Web Services Servers #
            # ------------------------- #

            # -----------------------#
            # SOAP Security Policies #
            # -----------------------#

            # ----------------- #
            # SOAP Web Services #
            # ----------------- #

            # ----------------- #
            # XMLRPC connectors #
            # ----------------- #

            # ----------------- #
            # XMLRPC Services   #
            # ----------------- #

            # ----------------- #
            # XMLRPC Servers    #
            # ----------------- #

            # ------------------------------- #
            # Activable Native Applications   #
            # ------------------------------- #
            # NIVR database type mysql|pgsql|oracle  
            ACTIVATE_APPLI_NIVR=no
            ACTIVATE_APPLI_CAASIVR=no
            ACTIVATE_OCCP_SNTS=no

            # ------------------------------- #
            # WebRTC                           #
            # ------------------------------- #

            # ----------------- #
            # Licensing         #
            # ------------------#
            # SIP stack licensing serial number for SEE and OCMP
            SEE_SIP_SERIAL="0BCN04-z8jWFC-VWXYAA-VVVVAA-VUzVAD-VQNVEB"
            # SIP stack licensing codeword for SEE and OCMP
            SEE_SIP_CODEWORD="0Emw03-z9pMFE-CDEF55-CCCC55-CDkC52-D2CC55-CeCC15"
            # SIP stack licensing codeword for OCMP same as SEE
            OCMP_SIPLIC_SERIAL=${SEE_SIP_SERIAL}
            OCMP_SIPLIC_CODEWORD=${SEE_SIP_CODEWORD}


            # --------------------------------------------------- #
            # Node receiving outgoing calls from SMB WebRTC client
            # Default: the NFV installed SIP load balancer VIP 
            # --------------------------------------------------- #
            WEBRTC_CALLEE_NAME=${VSIP_NAME}
            WEBRTC_CALLEE_IP_ADDR=${VSIP_IP_ADDR}

            # Optional list of RPM packages providing specific prompts
            APP_PROMPTS="/var/opt/OC/iso/hpoc-smb-demo-prompts*.rpm"

            # ------------------------------- #
            # Various database passwords 
            # ------------------------------- #
            # pgsql
            NIVRDB_OCDBROOT_PASSWORD=ocdbroot
            NIVRDB_OCDBREP_PASSWORD=ocdbrep
            NIVRDB_OCDBADMIN_PASSWORD=ocdbadmin
            NIVRDB_OCDBACCESS_PASSWORD=ocdbaccess
            NIVRDB_APPADMIN_PASSWORD=appadmin
            NIVRDB_APPACCESS_PASSWORD=appaccess

            # mysql: force strong passwords
            if [[ "$NIVR_DB_TYPE" == "mysql" ]] ; then
            NIVRDB_ROOT_PASSWORD=HP1nvent!
            NIVRDB_OCDBACCESS_PASSWORD=${NIVRDB_ROOT_PASSWORD}
            NIVRDB_OCDBREP_PASSWORD=${NIVRDB_ROOT_PASSWORD}
            fi


            # oracle
            TPDM_TABLESPACE=NFVTPDM_TS
            AAA_TABLESPACE=NFVAAA_TS
            MCM_TABLESPACE=NFVMCM_TS
            MCS_TABLESPACE=NFVMCS_TS
            SMB_TABLESPACE=NFVSMB_TS

            # Reporting System 
            NIVRDB_CCPS_DS_PASSWORD=CCPS_DS
            NIVRDB_CCPS_PASSWORD=CCPS
            NIVRDB_CCXML_PASSWORD=CCXML
            NIVRDB_EBRS_DS_PASSWORD=EBRS_DS
            NIVRDB_EBRS_QRTZ_PASSWORD=EBRS_QRTZ
            NIVRDB_EBRS_QRTZ_DS_PASSWORD=EBRS_QRTZ_DS
            NIVRDB_EBRS_PASSWORD=EBRS
            NIVRDB_JBOSS_JMS_PASSWORD=JBOSS_JMS
            NIVRDB_MSCML_PASSWORD=MSCML
            NIVRDB_REPORT_USER_PASSWORD=REPORT_USER
            NIVRDB_VXML_PASSWORD=CRYSTAL
            NIVRDB_QRTZ_DS_PASSWORD=QRTZ_DS
            NIVRDB_QRTZ_PASSWORD=QRTZ

            # ----------------------
            # USPM ISO image Details
            # ----------------------
            USPM_ISO_PATH=$(ls /var/opt/OC/iso/USPM*.iso 2> /dev/null)

            # Enable refresh by not deleting root ssh keys at the end of installation
            RETAIN_SSH_KEYS_ROOT=YES

            #-------------------------------------------
            # Legacy management based on MSE connectors 
            # Used to enable/disable features           
            #-------------------------------------------
            _legacySEE() {  command -v install-mse-connectors.sh install-mse_connectors.sh > /dev/null || test -f /var/opt/OC/iso/OpenCall-SEE*.iso && return 0 || return 1 ; }
            # NIVR and CaaS IVR: activate on SEE3 only
            # Messaging Framework, redis and all emscli resources: disable on SEE3
            if _legacySEE ; then
            MESSAGING_FRAMEWORK_SERVICE_COMPONENT_NAME=
            MESSAGING_GATEWAY_SERVICE_COMPONENT_NAME=
            ACTIVATE_APPLI_MESSAGING_FRAMEWORK=no
            ACTIVATE_APPLI_MESSAGING_GATEWAY=no
            TCAP_PROVIDER_NAME=()
            DIAMETER_SERVICE_COMPONENT_NAME=()
            UCP_PROVIDER_NAME=()
            SMPP_PROVIDER_NAME=()
            MRF_ADAPTER_SERVICE_COMPONENT_NAME=()
            DATASOURCE_NAME=()
            LDAP_PROFILE_NAME=()
            SOAP_SERVICE_COMPONENT_NAME=()
            SOAP_WSS_NAME=()
            SOAP_SECURITY_NAME=()
            SOAP_WS_NAME=()
            REDIS_HOST=()
            REDIS_IP_ADDR=()
            REDIS_INSTANCE_ID=()
            REDIS_PORT=()
            OCCP_SWITCHING_POINT=()
            OCCP_MEDIA_SERVER=()
            XMLRPC_SERVICE_COMPONENT_NAME=()
            XMLRPC_SERVICE=()
            XMLRPC_SERVER_ADDR=()
            else
            # NIVR native applications supported only on PostgreSQL database without WebRTC on SEE > 3
            ACTIVATE_APPLI_NIVR=$([[ $WEBRTC_SIGNALING_IP_ADDR == '' ]] && [[ $NIVR_DB_TYPE == 'pgsql' ]] && echo $ACTIVATE_APPLI_NIVR || echo no)
            ACTIVATE_APPLI_CAASIVR=no
            ACTIVATE_OCCP_SNTS=no
            fi

            # +++ EOF +++ # Do not delete this line
