---

- name: run collectInfo on sections MSE_NFV NIVR_NFV OCMP_NFV OCSNF_NFV
  raw: /opt/OC/bin/collectInfo -s MSE_NFV NIVR_NFV OCMP_NFV OCSNF_NFV -o /var/log

- name: Register collected information
  find: path=/var/log/collectInfo/
  register: collectedInfo

- name: fetch the collected info to local test directory
  with_items: "{{collectedInfo.files}}"
  loop_control:
    loop_var:
      _theFile
  fetch:
    src: "{{ _theFile.path }}"
    dest: test/
    flat: yes