---

- name: check for a refresh due to ISO image(s) change
  file:
    path: /var/opt/OC/iso/refresh_trigger.log
    state: absent
  notify: refresh MSE instance

- name: Copy uspm descriptor if any 
  copy:
    content: "{{ uspm_descriptor }}"
    dest: "{{ uspm_descriptor_path }}"
  when: uspm_descriptor_path != ''

- name: Copy app descriptor if any 
  copy:
    content: "{{ app_descriptor }}"
    dest: "{{ app_descriptor_path }}"
  when: app_descriptor_path != ''

- name: Copy descriptor to template 
  copy:
    content: "{{ descriptor }}"
    dest: /etc/opt/OC/hpoc-nivr-nfv/nivr-cluster-nfv.properties.erb

- name: resolve names and ip addresses in the template based on the inventory nick_name, hostname and ipaddress
  raw: |
    sed -i "s/_%_{{ hostvars[item].nick_name }}_hostname_%_/{{ hostvars[item].fqdn }}/g" /etc/opt/OC/hpoc-nivr-nfv/nivr-cluster-nfv.properties.erb &&
    sed -i "s/_%_{{ hostvars[item].nick_name }}_ipaddress_%_/{{ hostvars[item].ansible_ssh_host }}/g" /etc/opt/OC/hpoc-nivr-nfv/nivr-cluster-nfv.properties.erb
  with_items: "{{ groups['base'] }}"

- name: create the descriptor from the template and trigger a refresh in case of change
  copy:
    remote_src: yes
    src: "/etc/opt/OC/hpoc-nivr-nfv/nivr-cluster-nfv.properties.erb"
    dest: "/etc/opt/OC/hpoc-nivr-nfv/nivr-cluster-nfv.properties"
  notify: refresh MSE instance

- name: flush the handlers
  meta: flush_handlers

- name: create the descriptor and wait for the consolidated status
  raw: |
    sleep 2m && 
    until service nivr-nfv consolidated-status || (( $? > 127 )) ; do sleep 20s ; done 

- name: fetch the consolidated status log file to test/nivr-nfv.log
  fetch:
    src: /var/log/nivr-nfv.log
    dest: test/
    flat: yes

- name: return the actual consolidated status
  raw: service nivr-nfv consolidated-status

# (C) Copyright 2018 Hewlett Packard Enterprise Development LP.
