---
- name: Deploying MSE node(s)
  debug: 
    var=theNodeIpAddress

- name: Enable root at the console prompt
  shell: echo "root:hwroot" | chpasswd

- name: Apply CLOUD_ENVIRONMENT variables to /root/.bash_profile
  with_dict: "{{ lookup('env','CLOUD_ENVIRONMENT') }}"
  loop_control:
    loop_var:
      _env
  lineinfile: 
    path: /root/.bash_profile
    line: "export {{ _env.key }}={{ _env.value }}"

- name: Set dns names servers if defined
  lineinfile: 
    path: /etc/resolv.conf
    insertbefore: '^search.*'
    line: "nameserver  {{nameserver}}"
  when: nameserver is defined

- name: Set hostname
  hostname: 
    name: "{{theNodeHostname}}"

- name: Set OS signature {{osSignature}} in redhat-release
  copy:
    dest: /etc/redhat-release
    content: "{{osSignature}}"
  when: osSignature != ''

- name: Enforce name resolution to *not* use myhostname in /etc/nsswitch.conf for getent
  replace:
    dest=/etc/nsswitch.conf
    regexp='myhostname'
    replace=''
    backup=yes

- name: Create MSE directories
  with_items: ["{{isoRepo}}","{{isoMountPoint}}"]
  loop_control:
    loop_var:
      _dir
  file: 
    path: "{{_dir}}" 
    state: directory
    recurse: yes

- name: Get additional YUM repositories definitions
  with_items: "{{yumReposDef}}"
  loop_control:
    loop_var:
      _repo
  get_url:
    url: "{{yumReposDefUrl}}{{_repo}}"
    dest: "/etc/yum.repos.d"
  when: yumReposDef is defined

- name: Install createrepo for labdrops management
  yum:
    name: createrepo

- name: Get the MSE engine ISO image {{engineIso}} from cache {{cacheIso}}
  copy:
    src: "{{cacheIso}}{{engineIso}}"
    dest: "{{isoRepo}}"
  when: cacheIso is defined

- name: Get the MSE engine ISO image {{engineIso}} from remote {{isoUrl}}
  get_url:
    url: "{{isoUrl}}{{engineIso}}"
    dest: "{{isoRepo}}"
  notify: refresh MSE instance
  when: cacheIso is not defined

- name: Get the MSE product ISO images from cache {{cacheIso}}
  with_items: "{{mseProduct}}"
  loop_control:
    loop_var:
      _isoImage
  copy:
    src: "{{cacheIso}}{{_isoImage}}"
    dest: "{{isoRepo}}"
  notify: refresh MSE instance
  when: cacheIso is defined

- name: Get the MSE product ISO images from remote {{isoUrl}}
  with_items: "{{mseProduct}}"
  loop_control:
    loop_var:
      _isoImage
  get_url:
    url: "{{isoUrl}}{{_isoImage}}"
    dest: "{{isoRepo}}"
  when: cacheIso is not defined

- name: Remove unused ISO images if they are defined with a relative path to MSE_ISO_URL {{isoUrl}}
  shell: ls {{isoRepo}}*.iso | grep -v -e {{ engineIso }} -e {{' -e '.join((mseProduct )) }} | xargs rm -f
  when: isoUrl != ''

- name: Retrieve lab drops in {{isoRepo}} from cache {{cacheIso }}
  with_items: "{{mseLabDrops}}"
  loop_control:
    loop_var:
      _rpm
  copy:
    src: "{{cacheIso }}{{_rpm}}"
    dest: "{{isoRepo}}"
  notify: refresh MSE instance
  when: cacheIso is defined

- name: Retrieve lab drops in {{isoRepo}} from remote {{isoUrl}}
  with_items: "{{mseLabDrops}}"
  loop_control:
    loop_var:
      _rpm
  get_url:
    url: "{{isoUrl}}{{_rpm}}"
    dest: "{{isoRepo}}"
  notify: refresh MSE instance
  when: cacheIso is not defined

- name: Set the engine ISO image as a new variable _engineIso.stdout
  shell: |
    cd {{isoRepo}}
    ls ClusterManager*.iso 2> /dev/null || ls TAS*.iso 2> /dev/null || true
  register: _engineIso

- name: Get MSE engine installer install-cluster-manager.sh from {{isoRepo}}{{_engineIso.stdout}}
  iso_extract:
    image: "{{isoRepo}}{{_engineIso.stdout}}"
    dest: "{{isoRepo}}"
    files: "utils/install-cluster-manager.sh"

- name: Install versionlock plugin for yum
  yum: 
    name: yum-plugin-versionlock

- name: Install the MSE Automated Deployment engine
  shell: |
    > /etc/yum/pluginconf.d/versionlock.list
    cd {{isoRepo}} &&
    if test -f install-cluster-manager.sh ; then _theInstaller=cluster-manager && _theIso=ClusterManager*.iso  ; else _theInstaller=tas && _theIso=TAS*.iso ; fi 
    ./install-${_theInstaller}.sh --yes --install hpe-install-${_theInstaller} --disableplugin=yum-plugin-versionlock --iso ${_theIso} && 
    ./install-${_theInstaller}.sh --yes --install --with-hpoc-tls-certificates --with-hpe-mse-nfv --with-hpoc-uspm-nfv --enablerepo='{{yumRepo}}' --iso ${_theIso}

- name: Create a labdrops yum repository for rpm packages in {{isoRepo}} with labdrops {{mseLabDrops }}
  shell: |
    if find {{isoRepo}}*.rpm 2> /dev/null ; then
    cd {{isoRepo}} &&
    test -f install-cluster-manager.sh && _theInstaller=cluster-manager || _theInstaller=tas &&
    find {{isoRepo}}*.rpm -exec rpm -qp {} --qf '%{epoch}:%{name}-%{version}-%{release}.*\n' \; > /etc/yum/pluginconf.d/versionlock.list && /bin/cp -f /etc/yum/pluginconf.d/versionlock.list /etc/opt/OC/hpe-install-${_theInstaller}/versionlock.d/hpe-mse-nfv-999-versionlock.list &&
    > /etc/yum/pluginconf.d/versionlock.list
    fi
    createrepo --database {{isoRepo}}

- name: fill /etc/yum.repos.d/labdrops.repo file
  copy:
    dest: /etc/yum.repos.d/labdrops.repo
    content: |
      [labdrops]
      name=lab repository for development packages
      baseurl=file://{{isoRepo}}
      enabled=1
      gpgcheck=0

- name: Update with labdrops from {{isoRepo}}
  shell: |
    cd {{isoRepo}} &&
    if test -f install-cluster-manager.sh ; then _theInstaller=cluster-manager && _theIso=ClusterManager*.iso  ; else _theInstaller=tas && _theIso=TAS*.iso ; fi 
    ./install-${_theInstaller}.sh --yes --upgrade --enablerepo='{{yumRepo}}' --iso ${_theIso}

- name: Update with patches from cache if any
  with_dict: "{{patched_files}}"
  loop_control:
    loop_var:
      _patch
  copy:
    src: "{{cacheIso}}{{_patch.key}}"
    dest: "{{_patch.value}}"
  when: cacheIso is defined

- name: Update with patches from {{isoUrl}} if any
  with_dict: "{{patched_files}}"
  loop_control:
    loop_var:
      _patch
  get_url:
    url: "{{isoUrl}}{{_patch.key}}"
    dest: "{{_patch.value}}"
  when: cacheIso is not defined


- name: Install additional explicit packages from "{{yumRepo}}", ignoring errors
  with_items: "{{ yum_explicit_packages }}"
  loop_control:
    loop_var:
      _package
  yum:
    name: "{{_package}}"
    enablerepo: "{{yumRepo}}"
  ignore_errors: yes

- name: Define YUM exclude list {{yum_exclude}} in /etc/yum.conf
  lineinfile:
    path: /etc/yum.conf
    line: "exclude: {{yum_exclude}}"
    insertafter: "logfile"
  when: yum_exclude != ''

- name: Setup YUM version lock from {{isoUrl}}{{yum_version_lock}}, if any
  get_url:
    url: "{{isoUrl}}{{yum_version_lock}}"
    dest: "/etc/yum/pluginconf.d/versionlock.list"
    force: yes
  when: yum_version_lock != ''

- name: Start mandatory explicit services, if any
  with_items: "{{ mandatory_services }}"
  loop_control:
    loop_var:
      _service
  service:
    name: "{{_service}}"
    state: started

- name: Make sure the host is in /etc/hosts 
  shell: grep {{theNodeHostname}} /etc/hosts || echo {{theNodeIpAddress}} {{theNodeHostname}} >> /etc/hosts

- name: Enable sudo without tty since no password is required
  lineinfile: 
    path: /etc/sudoers
    regexp: "^Defaults    requiretty"
    line: "#Defaults    requiretty"

- name: Enable ssh for root and ocadmin with fixed keys
  shell: |
    sed -i "/^PasswordAuthentication.*no/d" /etc/ssh/sshd_config &&
    sed -i "s/#PasswordAuthentication.*/PasswordAuthentication yes/" /etc/ssh/sshd_config &&
    sed -i "/^PermitRootLogin.*no/d" /etc/ssh/sshd_config &&
    sed -i "s/#PermitRootLogin.*/PermitRootLogin yes/" /etc/ssh/sshd_config
- name: ocadmin ssh directory
  file: 
    path: '/home/ocadmin/.ssh'
    state: directory
    recurse: yes
    owner: 'ocadmin'
- name: root id_rsa.pub from cache {{cacheSshKeys}}
  copy:
    src: "{{cacheSshKeys}}id_rsa.pub"
    dest: "/root/.ssh/"
    mode: 0600
  when: cacheSshKeys is defined
- name: root id_rsa.pub from remote {{sshKeysUrl}}
  get_url:
    url: "{{sshKeysUrl}}id_rsa.pub"
    dest: "/root/.ssh/"
    mode: 0600
  when: cacheSshKeys is not defined
- name: root id_rsa from cache {{cacheSshKeys}}
  copy:
    src: "{{cacheSshKeys}}id_rsa"
    dest: "/root/.ssh/"
    mode: 0600
  when: cacheSshKeys is defined
- name: root id_rsa from remote {{sshKeysUrl}}
  get_url:
    url: "{{sshKeysUrl}}id_rsa"
    dest: "/root/.ssh/"
    mode: 0600
  when: cacheSshKeys is not defined
- name: root authorized_keys
  copy:
    remote_src: yes
    src: "/root/.ssh/id_rsa.pub"
    dest: "/root/.ssh/authorized_keys"
    mode: 0600
- name: ocadmin id_rsa.pub from cache {{cacheSshKeys}}
  copy:
    src: "{{cacheSshKeys}}id_rsa.pub"
    dest: "/home/ocadmin/.ssh/"
    owner: 'ocadmin'
    mode: 0600
  when: cacheSshKeys is defined
- name: ocadmin id_rsa.pub from remote {{sshKeysUrl}}
  get_url:
    url: "{{sshKeysUrl}}id_rsa.pub"
    dest: "/home/ocadmin/.ssh/"
    owner: 'ocadmin'
    mode: 0600
  when: cacheSshKeys is not defined
- name: ocadmin id_rsa from cache {{cacheSshKeys}}
  copy:
    src: "{{cacheSshKeys}}id_rsa"
    dest: "/home/ocadmin/.ssh/"
    owner: 'ocadmin'
    mode: 0600
  when: cacheSshKeys is defined
- name: ocadmin id_rsa from remote {{sshKeysUrl}}
  get_url:
    url: "{{sshKeysUrl}}id_rsa"
    dest: "/home/ocadmin/.ssh/"
    owner: 'ocadmin'
    mode: 0600
  when: cacheSshKeys is not defined
- name: ocadmin authorized_keys
  copy:
    remote_src: yes
    src: "/home/ocadmin/.ssh/id_rsa.pub"
    dest: "/home/ocadmin/.ssh/authorized_keys"
    owner: 'ocadmin'
    mode: 0600
- name: ssh_host private keys ecdsa ed25519 from cache {{cacheSshKeys}}
  with_items: ['ecdsa','ed25519']
  loop_control:
    loop_var:
      _aKeyType
  copy:
    src: "{{cacheSshKeys}}ssh_host_{{_aKeyType}}_key"
    dest: "/etc/ssh/"
    mode: 0640
  when: cacheSshKeys is defined
- name: ssh_host private keys ecdsa ed25519 from remote {{sshKeysUrl}}
  with_items: ['ecdsa','ed25519']
  loop_control:
    loop_var:
      _aKeyType
  get_url:
    url: "{{sshKeysUrl}}ssh_host_{{_aKeyType}}_key"
    dest: "/etc/ssh/"
    mode: 0640
  when: cacheSshKeys is not defined
- name: ssh_host private keys rsa from cache {{cacheSshKeys}}
  with_items: ['rsa']
  loop_control:
    loop_var:
      _aKeyType
  copy:
    src: "{{cacheSshKeys}}ssh_host_{{_aKeyType}}_key"
    dest: "/etc/ssh/"
    mode: 0600
  when: cacheSshKeys is defined
- name: ssh_host private keys rsa from remote {{sshKeysUrl}}
  with_items: ['rsa']
  loop_control:
    loop_var:
      _aKeyType
  get_url:
    url: "{{sshKeysUrl}}ssh_host_{{_aKeyType}}_key"
    dest: "/etc/ssh/"
    mode: 0600
  when: cacheSshKeys is not defined
- name: ssh_host public keys ecdsa ed25519 rsa from cache {{cacheSshKeys}}
  with_items: ['ecdsa','ed25519','rsa']
  loop_control:
    loop_var:
      _aKeyType
  copy:
    src: "{{cacheSshKeys}}ssh_host_{{_aKeyType}}_key.pub"
    dest: "/etc/ssh/"
    mode: 0644
  when: cacheSshKeys is defined
- name: ssh_host public keys ecdsa ed25519 rsa from remote {{sshKeysUrl}}
  with_items: ['ecdsa','ed25519','rsa']
  loop_control:
    loop_var:
      _aKeyType
  get_url:
    url: "{{sshKeysUrl}}ssh_host_{{_aKeyType}}_key.pub"
    dest: "/etc/ssh/"
    mode: 0644
  when: cacheSshKeys is not defined
- name: Restart service sshd
  service:
    name: sshd
    state: restarted

# mse nfv services needs to be started only if not already successfully completed
# ignore start error, as this can mean that the service is already running
# Do not trust the status if the log file is missing (uspm status returns 0 even if the service has never run)
- name: Start all MSE engines services
  with_items: ['nivr','ocmp','ocsnf','uspm']
  loop_control:
    loop_var:
      vnfc
  shell: service {{vnfc}}-nfv status && test -f /var/log/{{vnfc}}-setup.log || service {{vnfc}}-nfv start || echo started

# (C) Copyright 2018 Hewlett Packard Enterprise Development LP.